runtime: java17

instance_class: F2

service: backend

handlers:
  - url: /.*
    script: auto

env_variables:
  SPRING_DATASOURCE_URL: 'jdbc:mysql://35.199.93.168:3306/zoo_db?useSSL=false&allowPublicKeyRetrieval=true'
  SPRING_DATASOURCE_USERNAME: 'zooUser1'
  SPRING_DATASOURCE_PASSWORD: 'A$mqP*YJFQig=OvJ'
